name:
  maximum_length: 50
password:
  minimum_length: 6
email:
  maximum_length: 255
remember_me:
  checked: "1"
mailer:
  default: "nmduc3@gmail.com"
user:
  index: 20
  show_buy_request: 4
  show_activities: 5
buy_requests:
  index: 10
home:
  show_activities_feed: 10
book:
  index: 20
activity:
  comment: "comment"
